name: Release module version

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    uses: urob/zmk-actions/.github/workflows/upgrade-module.yml@9ebfa3ed81027d7907a8629f2085ae72e4c03b80 # v11.0.2
