name: Release module version

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    uses: urob/zmk-actions/.github/workflows/upgrade-module.yml@ba0a55737f5f8c03a39cbb7cbd22cefbec0caf26 # v11.0.3
