name: Release module version

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    uses: urob/zmk-actions/.github/workflows/upgrade-module.yml@2d0dce4d9584d7c43f6a7ef0aa9e04dcd2afa8fe # v12.0.0
