name: Check for new ZMK releases

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *" # Run daily at 22:00 UTC

permissions:
  contents: write

jobs:
  upgrade-zmk:
    uses: urob/zmk-actions/.github/workflows/upgrade-zmk.yml@12401d756af5e640fe29af8910d03d292d240cbb # v10.0.0
    secrets:
      # Name of PAT with write access to pull requests
      token: ${{ secrets.ZMK_ACTIONS_TOKEN }}
