name: Check for new ZMK releases

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *" # Run daily at 22:00 UTC

permissions:
  contents: write

jobs:
  upgrade-zmk:
    uses: urob/zmk-actions/.github/workflows/upgrade-zmk.yml@e89b7f5bd1226bc6cf9d20c12e649dc44b0a24a2 # v12.2.0
    secrets:
      # Name of PAT with write access to pull requests
      token: ${{ secrets.ZMK_ACTIONS_TOKEN }}
