name: Check for new ZMK releases

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *" # Run daily at 22:00 UTC

permissions:
  contents: write

jobs:
  upgrade-zmk:
    uses: urob/zmk-actions/.github/workflows/upgrade-zmk.yml@2d0dce4d9584d7c43f6a7ef0aa9e04dcd2afa8fe # v12.0.0
    secrets:
      # Name of PAT with write access to pull requests
      token: ${{ secrets.ZMK_ACTIONS_TOKEN }}
